<a href="https://colab.research.google.com/github/shaharbanu-123/FINAL-Project/blob/main/Comparison%20of%20Models%20%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd

# Step 1: Define your model performance data
data = {
    'Model': ['GRU', 'LSTM', 'CNN'],
    'RMSE': [70.18, 70.97, 90.74],
    'MAE': [50.46, 49.95, 66.68],
    'MAPE (%)': [34.40, 29.73, 38.08],
    'R²': [0.18, 0.16, -0.37],
    'Forecast Accuracy (%)': [65.60, 70.27, 61.92]
}

df = pd.DataFrame(data)

# Step 2: Rank each metric (lower is better for errors, higher is better for R² and accuracy)
df['Rank_RMSE'] = df['RMSE'].rank(ascending=True)
df['Rank_MAE'] = df['MAE'].rank(ascending=True)
df['Rank_MAPE'] = df['MAPE (%)'].rank(ascending=True)
df['Rank_R2'] = df['R²'].rank(ascending=False)
df['Rank_Accuracy'] = df['Forecast Accuracy (%)'].rank(ascending=False)

# Step 3: Calculate average rank
df['Average Rank'] = df[['Rank_RMSE', 'Rank_MAE', 'Rank_MAPE', 'Rank_R2', 'Rank_Accuracy']].mean(axis=1)

# Step 4: Sort by average rank
df = df.sort_values('Average Rank').reset_index(drop=True)

# Optional: Format and highlight for display
styled = df.style.background_gradient(cmap='RdYlGn_r').highlight_min(subset=['Average Rank', 'Rank_RMSE', 'Rank_MAE', 'Rank_MAPE', 'Rank_R2', 'Rank_Accuracy'], color='red') .highlight_max(subset=['Average Rank', 'Rank_RMSE', 'Rank_MAE', 'Rank_MAPE', 'Rank_R2', 'Rank_Accuracy'], color='green').format({
    'RMSE': "{:.2f}",
    'MAE': "{:.2f}",
    'MAPE (%)': "{:.2f}",
    'R²': "{:.2f}",
    'Forecast Accuracy (%)': "{:.2f}",
    'Average Rank': "{:.2f}"
})

styled